# Generated by Django 5.2.7 on 2025-10-27 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.PositiveIntegerField(help_text='Maintenance contract duration in months')),
                ('interval', models.PositiveIntegerField(help_text='Months between maintenance visits')),
                ('next_maintenance_date', models.DateField(blank=True, db_index=True, null=True)),
            ],
            options={
                'ordering': ['next_maintenance_date'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('warranty_years', models.PositiveIntegerField(default=0)),
                ('warranty_months', models.PositiveIntegerField(default=0)),
                ('warranty_days', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
