# Generated by Django 5.2.7 on 2025-11-14 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenance',
            name='maintenance_number',
        ),
    ]
