# Generated by Django 5.2.7 on 2025-10-24 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='warranty_duration',
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='project',
            name='warranty_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
