# Generated by Django 5.2.7 on 2025-12-05 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_issued_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='desposit_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
