# Generated by Django 5.2.7 on 2025-12-05 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_invoice_desposit_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='desposit_date',
            new_name='deposit_date',
        ),
    ]
