# Generated by Django 5.2.7 on 2025-11-23 13:59

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('wilaya', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('tax_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID/Matricule')),
                ('website', models.URLField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='supplier_su_name_b8b3c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(help_text='Description of the debt/purchase')),
                ('date', models.DateField(db_index=True)),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total amount of the debt', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('paid_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount already paid', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reference_number', models.CharField(blank=True, max_length=100, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('is_paid', models.BooleanField(db_index=True, default=False)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to='supplier.supplier')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['supplier', 'date'], name='supplier_de_supplie_68d767_idx'), models.Index(fields=['is_paid', 'due_date'], name='supplier_de_is_paid_b802ee_idx')],
            },
        ),
    ]
