# Generated by Django 5.2.7 on 2025-11-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.JSONField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=50)),
                ('fax', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('is_corporate', models.BooleanField(default=False)),
                ('rc', models.CharField(blank=True, max_length=100, null=True)),
                ('nif', models.CharField(blank=True, max_length=100, null=True)),
                ('nis', models.CharField(blank=True, max_length=100, null=True)),
                ('ai', models.CharField(blank=True, max_length=100, null=True)),
                ('art', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
