# Generated by Django 5.2.7 on 2025-11-23 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('PROJECT_ASSIGNED', 'Assigned to Project'), ('PROJECT_STARTING_SOON', 'Project Starting Soon'), ('PROJECT_MODIFIED', 'Project Modified'), ('PROJECT_DELETED', 'Project Deleted'), ('MAINTENANCE_STARTING_SOON', 'Maintenance Starting Soon'), ('MAINTENANCE_ADDED', 'Maintenance Added'), ('MAINTENANCE_MODIFIED', 'Maintenance Modified'), ('MAINTENANCE_DELETED', 'Maintenance Deleted')], db_index=True, max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], db_index=True, default='MEDIUM', max_length=20)),
                ('data', models.JSONField(blank=True, help_text='Additional data in JSON format', null=True)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_project_assigned', models.BooleanField(default=True)),
                ('enable_project_starting_soon', models.BooleanField(default=True)),
                ('enable_project_modified', models.BooleanField(default=True)),
                ('enable_project_deleted', models.BooleanField(default=True)),
                ('enable_maintenance_starting_soon', models.BooleanField(default=True)),
                ('enable_maintenance_added', models.BooleanField(default=True)),
                ('enable_maintenance_modified', models.BooleanField(default=True)),
                ('enable_maintenance_deleted', models.BooleanField(default=True)),
                ('enable_sound', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
            },
        ),
    ]
