# Generated by Django 5.2.7 on 2025-11-25 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_updates'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_is_conf_e20f56_idx',
            old_name='notificatio_is_conf_idx',
        ),
    ]
